const CONFIG_KEY='uchi-ha-config-v2';
const FAVORITES_KEY='uchi-favorites-v1';
const $=s=>document.querySelector(s);
let config=read(CONFIG_KEY,{}), favorites=read(FAVORITES_KEY,[]), states=[], demo=false, toastTimer;
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function friendly(s){return s.attributes?.friendly_name||s.entity_id.split('.').pop().replaceAll('_',' ')}
function domainOf(s){return s.entity_id.split('.')[0]}
function isActive(s){return !['off','unavailable','unknown','closed'].includes(s.state)}
function deviceRoom(s){const a=s.attributes||{};if(a.area_name||a.room)return a.area_name||a.room;const n=(a.friendly_name||'').trim();const known=[['リビング','リビング'],['居間','リビング'],['寝室','寝室'],['子ども部屋','子ども部屋'],['キッチン','キッチン'],['台所','キッチン'],['玄関','玄関'],['浴室','浴室'],['書斎','書斎'],['ダイニング','ダイニング'],['Living Room','リビング'],['Bedroom','寝室'],['Kitchen','キッチン']];const hit=known.find(([prefix])=>n.toLowerCase().startsWith(prefix.toLowerCase()));if(hit)return hit[1];const id=s.entity_id.split('.')[1];const prefixes=[['living_room','リビング'],['living','リビング'],['bedroom','寝室'],['kitchen','キッチン'],['entrance','玄関'],['bathroom','浴室'],['office','書斎'],['dining','ダイニング'],['hallway','廊下']];return prefixes.find(([p])=>id.startsWith(p+'_'))?.[1]||'その他'}
function roomIcon(room){return ({'リビング':'⌂','寝室':'☾','キッチン':'♨','玄関':'↗','浴室':'≈','書斎':'▤','ダイニング':'◉','その他':'⌂'})[room]||'⌂'}
function controlled(s){return ['light','switch','fan','cover','input_boolean','climate','humidifier','lock','vacuum'].includes(domainOf(s))}
function roomDevices(){return states.filter(controlled)}
function notify(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
function status(connected,label=connected?'接続中':'未接続'){ $('#connectionLabel').textContent=label;$('#connectionHost').textContent=connected?new URL(config.url).host:'Home Assistant';$('#connectionDot').classList.toggle('connected',connected);$('#settingsStatus').textContent=label;$('#settingsStatus').classList.toggle('connected',connected); }
async function ha(path,options={}){const response=await fetch(`${config.url.replace(/\/$/,'')}${path}`,{...options,headers:{Authorization:`Bearer ${config.token}`,'Content-Type':'application/json',...(options.headers||{})}});if(!response.ok)throw Error(`${response.status} ${response.statusText}`);return response.status===204?null:response.json()}
function setPage(page){if(!['home','devices','scenes','settings'].includes(page))page='home';document.querySelectorAll('.page').forEach(el=>el.classList.toggle('active',el.dataset.view===page));document.querySelectorAll('[data-page]').forEach(el=>el.classList.toggle('active',el.dataset.page===page));$('#pageLabel').textContent=({home:'ホーム',devices:'デバイス',scenes:'シーン',settings:'接続・設定'})[page];if(page==='settings'){ $('#haUrl').value=config.url||'';$('#haToken').value=config.token||''; }if(page==='devices')renderDevices();history.replaceState(null,'',`#${page}`)}
function domainLabel(d){return ({light:'照明',switch:'スイッチ',climate:'エアコン',cover:'カーテン',fan:'ファン',input_boolean:'スイッチ',humidifier:'加湿器',lock:'鍵',vacuum:'掃除機'})[d]||'デバイス'}
function readableState(s){const d=domainOf(s);if(s.state==='unavailable')return 'オフライン';if(d==='climate')return `${s.state==='off'?'停止中':({heat:'暖房',cool:'冷房',dry:'除湿',fan_only:'送風',auto:'自動'}[s.state]||s.state)}${s.attributes.temperature!=null?` · ${s.attributes.temperature}°`:''}`;if(d==='cover')return s.state==='open'?'開':'閉';if(d==='lock')return s.state==='locked'?'施錠':'解錠';return isActive(s)?'オン':'オフ'}
function deviceCard(s){const d=domainOf(s),on=isActive(s),icon=({light:'◉',switch:'⏻',climate:'❄',cover:'▤',fan:'✣',humidifier:'≈',lock:'▣',vacuum:'◌'})[d]||'⌁';let control='';if(d==='climate'&&s.state!=='off')control=`<div class="climate-control"><button data-climate="down" data-entity="${escapeHtml(s.entity_id)}" aria-label="設定温度を下げる">−</button><b>${escapeHtml(s.attributes.temperature??'—')}°</b><button data-climate="up" data-entity="${escapeHtml(s.entity_id)}" aria-label="設定温度を上げる">+</button></div>`;if(d==='light'&&s.attributes.brightness!=null&&on)control=`<label class="brightness-control"><span>明るさ</span><input type="range" min="1" max="100" value="${Math.round(s.attributes.brightness/255*100)}" data-brightness="${escapeHtml(s.entity_id)}"><b>${Math.round(s.attributes.brightness/255*100)}%</b></label>`;return `<article class="device-card ${on?'is-on':''}"><div class="device-card-top"><span class="device-glyph">${icon}</span><button class="favorite-button ${favorites.includes(s.entity_id)?'selected':''}" data-favorite="${escapeHtml(s.entity_id)}" aria-label="お気に入り切替">${favorites.includes(s.entity_id)?'★':'☆'}</button></div><div class="device-name">${escapeHtml(friendly(s))}</div><div class="device-detail">${escapeHtml(deviceRoom(s))} ・ ${domainLabel(d)} <span>· ${escapeHtml(readableState(s))}</span></div>${control}<div class="device-card-bottom"><span class="state-text ${on?'active':''}"><i></i>${escapeHtml(readableState(s))}</span><button class="toggle ${on?'on':''}" role="switch" aria-checked="${on}" aria-label="${escapeHtml(friendly(s))}の切り替え" data-toggle="${escapeHtml(s.entity_id)}"></button></div></article>`}
function sceneCard(s,index=0){const symbols=['☀','☾','↗','✦'];return `<button class="scene-card tone-${index%4}" data-scene="${escapeHtml(s.entity_id)}"><span class="scene-icon">${symbols[index%symbols.length]}</span><span class="scene-copy"><b>${escapeHtml(friendly(s))}</b><small>タップして実行</small></span><span class="scene-arrow">→</span></button>`}
function empty(title,body,action=''){return `<div class="empty-state"><span>⌂</span><b>${title}</b><p>${body}</p>${action}</div>`}
function renderSummary(){const devices=roomDevices(),lights=devices.filter(s=>domainOf(s)==='light'),rooms=[...new Set(devices.map(deviceRoom))],scenes=states.filter(s=>domainOf(s)==='scene');$('#lightCount').textContent=`${lights.filter(isActive).length} / ${lights.length} 点灯中`;$(`#otherCount`).textContent=`${devices.filter(s=>domainOf(s)!=='light').length} 台`;$('#roomCount').textContent=`${rooms.length} 部屋`;$('#sceneCount').textContent=`${scenes.length} 個`;$(`#summary`).textContent=demo?'デモ表示中です。設定からHome Assistantに接続できます。':devices.length?`${devices.length} 台のデバイスを${rooms.length} 部屋から確認できます。`:'Home Assistantに接続すると、デバイスの状態を確認できます。';$('#heroTitle').textContent=devices.length?`${lights.filter(isActive).length} 台の照明が点灯中`:'家の状態をチェックしましょう';$('#heroSub').textContent=devices.length?`${devices.length} 台のデバイスが接続されています。`:'Home Assistantに接続すると、デバイスを操作できます。';$('#heroAction').textContent=config.token&&!demo?'デバイスを操作する →':'接続する →';const fav=devices.filter(s=>favorites.includes(s.entity_id)).slice(0,4);const featured=fav.length?fav:devices.filter(isActive).slice(0,4);$('#favoriteGrid').innerHTML=featured.length?featured.map(deviceCard).join(''):empty('よく使うデバイスはここに表示されます','デバイス一覧の☆を押して登録してください。',`<button class="button secondary" data-page="devices">デバイス一覧へ →</button>`);const topScenes=scenes.slice(0,3);$('#homeScenes').innerHTML=topScenes.length?topScenes.map(sceneCard).join(''):empty('シーンがありません','Home Assistantでシーンを作成すると、ここから実行できます。');$('#homeScenes').classList.toggle('empty-holder',!topScenes.length);renderScenes();renderFilters();bindControls()}
function renderDevices(){const q=$('#deviceSearch').value.trim().toLowerCase(),room=$('#roomFilter').value,domain=$('#domainFilter').value;const list=roomDevices().filter(s=>{const d=domainOf(s);return (!q||friendly(s).toLowerCase().includes(q)||s.entity_id.toLowerCase().includes(q))&&(room==='all'||deviceRoom(s)===room)&&(domain==='all'||d===domain||(domain==='other'&&!['light','switch','climate','cover','fan'].includes(d))) });$('#deviceResults').textContent=`${list.length} 台のデバイス`;$('#deviceGrid').innerHTML=list.length?list.map(deviceCard).join(''):empty(roomDevices().length?'条件に合うデバイスがありません':'デバイスがありません',roomDevices().length?'検索条件やフィルターを変えてみてください':'接続設定からHome Assistantに接続してください。');bindControls()}
function renderScenes(){const scenes=states.filter(s=>domainOf(s)==='scene');$('#sceneList').innerHTML=scenes.length?scenes.map((s,i)=>`<div class="scene-list-item">${sceneCard(s,i)}</div>`).join(''):empty('シーンがありません','Home Assistantの「設定 → オートメーションとシーン」から作成してください。')}
function renderFilters(){const select=$('#roomFilter'),selected=select.value,rooms=[...new Set(roomDevices().map(deviceRoom))];select.innerHTML='<option value="all">すべての部屋</option>'+rooms.map(r=>`<option value="${escapeHtml(r)}">${escapeHtml(r)}</option>`).join('');if(rooms.includes(selected))select.value=selected}
function render(){renderSummary();renderDevices()}
async function refresh(){if(demo){render();notify('デモ画面を更新しました');return}if(!config.url||!config.token){setPage('settings');return}try{states=await ha('/api/states');status(true);render();notify('最新の状態に更新しました')}catch(e){status(false,'接続エラー');notify('更新できません。接続を確認してください。')}}
function sampleStates(){const mk=(id,name,state='off',domain='light',attrs={})=>({entity_id:`${domain}.${id}`,state,attributes:{friendly_name:name,...attrs}});return[mk('living_main','リビング メインライト','on'),mk('living_floor','リビング フロアライト','off','light',{brightness:125}),mk('living_ac','リビング エアコン','cool','climate',{temperature:25,current_temperature:26}),mk('bedroom_light','寝室 ライト'),mk('kitchen_pendant','キッチン ペンダント','on'),mk('curtain','リビング カーテン','open','cover'),mk('humidifier','寝室 加湿器','on','humidifier'),{entity_id:'scene.morning',state:'scening',attributes:{friendly_name:'おはよう'}},{entity_id:'scene.good_night',state:'scening',attributes:{friendly_name:'おやすみ'}},{entity_id:'scene.away',state:'scening',attributes:{friendly_name:'おでかけ'}}]}
async function connect(){const url=$('#haUrl').value.trim().replace(/\/$/,''),token=$('#haToken').value.trim(),err=$('#connectError');err.textContent='';if(!url||!token){err.textContent='URLとアクセストークンの両方を入力してください。';return}try{new URL(url)}catch{err.textContent='URLの形式を確認してください。';return}$('#connectButton').disabled=true;$('#connectButton').textContent='接続を確認しています…';const old=config;config={url,token};try{const api=await ha('/api/');if(!api?.message)throw Error('API応答を確認できません');states=await ha('/api/states');localStorage.setItem(CONFIG_KEY,JSON.stringify(config));demo=false;status(true);render();setPage('home');notify('Home Assistantに接続しました')}catch(e){config=old;err.textContent=e.message.startsWith('Failed to fetch')?'接続できません。GitHub PagesのURLをHome AssistantのCORS許可に追加し、Home AssistantもHTTPSで公開してください。':'接続できませんでした。URLとトークンを確認してください。'}finally{$('#connectButton').disabled=false;$('#connectButton').innerHTML='接続してデバイスを読み込む <span>→</span>'}}
async function toggleDevice(entity){if(demo){const s=states.find(x=>x.entity_id===entity);s.state=isActive(s)?'off':'on';render();notify(`${friendly(s)}を${isActive(s)?'オン':'オフ'}にしました`);return}const s=states.find(x=>x.entity_id===entity),d=domainOf(s);let service=isActive(s)?'turn_off':'turn_on';if(d==='cover')service=isActive(s)?'close_cover':'open_cover';if(d==='lock')service=isActive(s)?'lock':'unlock';if(d==='vacuum')service=isActive(s)?'return_to_base':'start';try{await ha(`/api/services/${d}/${service}`,{method:'POST',body:JSON.stringify({entity_id:entity})});await refresh();notify(`${friendly(s)}を操作しました`)}catch{notify('操作できません。Home Assistantの状態を確認してください。')}}
async function scene(entity){if(demo){notify(`${friendly(states.find(s=>s.entity_id===entity))}を実行しました`);return}try{await ha('/api/services/scene/turn_on',{method:'POST',body:JSON.stringify({entity_id:entity})});await refresh();notify('シーンを実行しました')}catch{notify('シーンを実行できませんでした')}}
async function climateTemp(entity,delta){const s=states.find(x=>x.entity_id===entity),temp=Number(s.attributes.temperature||20)+delta;if(demo){s.attributes.temperature=temp;render();return}try{await ha('/api/services/climate/set_temperature',{method:'POST',body:JSON.stringify({entity_id:entity,temperature:temp})});await refresh()}catch{notify('温度を変更できませんでした')}}
async function brightness(entity,value){if(demo){const s=states.find(x=>x.entity_id===entity);s.attributes.brightness=Math.round(value/100*255);render();return}try{await ha('/api/services/light/turn_on',{method:'POST',body:JSON.stringify({entity_id:entity,brightness_pct:Number(value)})});states=await ha('/api/states');render()}catch{notify('明るさを変更できませんでした')}}
function bindControls(){document.querySelectorAll('[data-toggle]').forEach(el=>el.onclick=()=>toggleDevice(el.dataset.toggle));document.querySelectorAll('[data-scene]').forEach(el=>el.onclick=()=>scene(el.dataset.scene));document.querySelectorAll('[data-favorite]').forEach(el=>el.onclick=()=>{const id=el.dataset.favorite;favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];localStorage.setItem(FAVORITES_KEY,JSON.stringify(favorites));render()});document.querySelectorAll('[data-climate]').forEach(el=>el.onclick=()=>climateTemp(el.dataset.entity,el.dataset.climate==='up'?1:-1));document.querySelectorAll('[data-brightness]').forEach(el=>el.onchange=()=>brightness(el.dataset.brightness,el.value))}
function bind(){document.addEventListener('click',e=>{const nav=e.target.closest('[data-page]');if(nav){setPage(nav.dataset.page);return}const btn=e.target.closest('#sidebarSettings');if(btn)setPage('settings')});$('#heroAction').onclick=()=>config.token&&!demo?setPage('devices'):setPage('settings');$('#refresh').onclick=refresh;$('#deviceRefresh').onclick=refresh;$('#connectButton').onclick=connect;$('#disconnectButton').onclick=()=>{localStorage.removeItem(CONFIG_KEY);config={};states=[];demo=false;status(false);render();setPage('settings');notify('接続情報を削除しました')};$('#demoButton').onclick=()=>{states=sampleStates();demo=true;config={};status(false,'デモ表示中');render();setPage('home');notify('サンプルデータを表示しました')};$('#deviceSearch').oninput=renderDevices;$('#roomFilter').onchange=renderDevices;$('#domainFilter').onchange=renderDevices;window.addEventListener('hashchange',()=>setPage(location.hash.slice(1)));}
function setup(){const now=new Date();$('#dateLabel').textContent=new Intl.DateTimeFormat('ja-JP',{month:'long',day:'numeric',weekday:'short'}).format(now);const h=now.getHours();$('#greeting').textContent=h<11?'おはようございます':h<17?'こんにちは':'おかえりなさい';bind();if(config.url&&config.token){ha('/api/states').then(data=>{states=data;status(true);render()}).catch(()=>status(false,'接続エラー'))}else{render();status(false)}const initial=location.hash.slice(1);setPage(['home','devices','scenes','settings'].includes(initial)?initial:'home');if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
setup();
